/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MainMenu.java
 *
 * Created on Mar 5, 2013, 9:33:32 AM
 */
package FileAccess.ScannerFileReaderAndPrintWritter;

import javax.swing.JOptionPane;


/**
 * PDDA classes - menu example
 *  
 * The menu call initialise (and thus loaded everything in memory)
 * The menu will again call terminate (and thus save everything to a file)

 * @author S ribeiro
 */
public class MainMenu extends javax.swing.JFrame
{
    /** Creates new form MainMenu */
    public MainMenu()
    {
        initComponents();

        try
        {
            Customer.initialise();
        }
        catch (DataStorageException ex)
        {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage());
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnuClose = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mnuAddCustomer = new javax.swing.JMenuItem();
        mnuCustInfo = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Customer Application - S Ribeiro");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jMenu1.setText("File");

        mnuClose.setText("Close");
        mnuClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCloseActionPerformed(evt);
            }
        });
        jMenu1.add(mnuClose);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenu2.setActionCommand("Customer");

        mnuAddCustomer.setText("Add Customer");
        mnuAddCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAddCustomerActionPerformed(evt);
            }
        });
        jMenu2.add(mnuAddCustomer);

        mnuCustInfo.setText("Customer Information");
        mnuCustInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCustInfoActionPerformed(evt);
            }
        });
        jMenu2.add(mnuCustInfo);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void mnuCloseActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_mnuCloseActionPerformed
    {//GEN-HEADEREND:event_mnuCloseActionPerformed
        terminateDataStorage();

        //terminate the application
        dispose();
        System.exit(0);
    }//GEN-LAST:event_mnuCloseActionPerformed

    private void mnuAddCustomerActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_mnuAddCustomerActionPerformed
    {//GEN-HEADEREND:event_mnuAddCustomerActionPerformed
        AddCustomerScreen screen = new AddCustomerScreen();
        screen.setVisible(true);
    }//GEN-LAST:event_mnuAddCustomerActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt)//GEN-FIRST:event_formWindowClosing
    {//GEN-HEADEREND:event_formWindowClosing
        terminateDataStorage();
    }//GEN-LAST:event_formWindowClosing

    private void mnuCustInfoActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_mnuCustInfoActionPerformed
    {//GEN-HEADEREND:event_mnuCustInfoActionPerformed
        ViewCustomerScreen screen = new ViewCustomerScreen();
        screen.setVisible(true);
    }//GEN-LAST:event_mnuCustInfoActionPerformed

    
    private void terminateDataStorage()
    {
       try
        {
            Customer.terminate();
        }
        catch (DataStorageException ex)
        {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage());
        } 
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        java.awt.EventQueue.invokeLater(new Runnable()
        {

            public void run()
            {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem mnuAddCustomer;
    private javax.swing.JMenuItem mnuClose;
    private javax.swing.JMenuItem mnuCustInfo;
    // End of variables declaration//GEN-END:variables
}
